### ISSUE TITLE
Failed to run udevadm: No such file or directory

### ISSUE THREAD

**Issue by shitpoet** [ellbur/totalmapper#10]
When trying to install tarball version of the utility as a system service:

```
$ sudo totalmapper add_systemd_service --layout-file /home/ors/config/keys.json
Failed to run udevadm: No such file or directory (os error 2)
```

On my Debian 11 `udevadm` is in `/bin`, and not in `/usr/bin`.

The same problem is with `systemctl`.

I managed to install the service by making two symlinks:

```
$ sudo ln -s /bin/udevadm /usr/bin/udevadm
```

```
$ sudo ln -s /bin/systemctl /usr/bin/systemctl
```

As far as I understand it is connected with [`usr` merge process in Debian](https://wiki.debian.org/UsrMerge)

I have not installed `usrmerge` package, and `apt` didnt it for me too. Maybe it would resolve the problem automatically.

**Comment by ellbur** [comment]
Thank you for pointing out this problem. It should hopefully be fixed by 4bda5089912888e7035f3a7dafffe6bd952af119.
