### ISSUE TITLE
Modifiers continue to be pressed

### ISSUE THREAD

**Issue by Shatur** [ellbur/totalmapper#16]
The following configuration works and <kbd>Meta</kbd>+<kbd>1</kbd> results in <kbd>|</kbd>, but <kbd>Meta</kbd> also registered as released and results into opening "start" menu: 
```json
{
  "mappings": [
    { "from": [ "LEFTMETA", "1" ], "to": ["LEFTSHIFT", "BACKSLASH"] }
  ]
}
```

**Comment by ellbur** [comment]
Sorry for the long delay. I will try this out.

**Comment by ellbur** [comment]
Ah, I see the issue. When you first press <kbd>Meta</kbd>, `totalmapper` can't know you're about to use it as a modifier, so it has to initially register it as pressed.

If you want to tell `totalmapper` that <kbd>Meta</kbd> is always a modifier, you can map the key itself to nothing:

```json
 {
  "mappings": [
    { "from": [ "LEFTMETA", "1" ], "to": ["LEFTSHIFT", "BACKSLASH"] },
    { "from": [ "LEFTMETA" ], "to": [] }
  ]
}
```

**Comment by Shatur** [comment]
Thanks!
