### ISSUE TITLE
"TAB" does not work as a modifier key

### ISSUE THREAD

**Issue by senbrow** [ellbur/totalmapper#7]
### Expected behavior

The following mapping should map the DHTN keys to "arrow" keypresses while tab is held:

```
{
    "mappings": [
        { "from": [ "TAB", "D" ], "to": [ "LEFT" ] },
        { "from": [ "TAB", "H" ], "to": [ "DOWN" ] },
        { "from": [ "TAB", "T" ], "to": [ "UP" ] },
        { "from": [ "TAB", "N" ], "to": [ "RIGHT" ] }
    ]
}
```

### Actual behavior
keypresses appear to pass through as if the mapping was not in effect (e.g. holding TAB and hitting the D key results in <tabstop><d> in a text editor).

**Comment by ellbur** [comment]
Hi @senbrow,

Do any mappings work for you?

I notice that the keys you are using (DHTN) are in a line on a Dvorak keyboard. Because `totalmapper` uses keycodes directly from the kernel, you may need to specify your mappings using the corresponding QWERTY keys:

```
{
    "mappings": [
        { "from": [ "TAB" ], "to": [  ] },
        { "from": [ "TAB", "H" ], "to": [ "LEFT" ] },
        { "from": [ "TAB", "J" ], "to": [ "DOWN" ] },
        { "from": [ "TAB", "K" ], "to": [ "UP" ] },
        { "from": [ "TAB", "L" ], "to": [ "RIGHT" ] }
    ]
}
```

**Comment by ellbur** [comment]
Hi @senbrow,

Thanks for the pull request and for clarifying the README. It's very helpful. 

If you want to change your keycodes to match your DVORAK keyboard, you can see how to [map scancodes to keycodes](https://wiki.archlinux.org/title/map_scancodes_to_keycodes). But that might be too much trouble.
